name: Run tests

on: [push]

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: ['3.10', '3.11', '3.12.6', '3.12.7']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install xarray pytest pooch numpy netcdf4
    - name: List installed deps
      run: pip list
    - name: print xr info
      run: python -c "import xarray as xr; xr.show_versions()"
    - name: Run Tests
      run: pytest --color=yes .